name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - uses: mydea/actions-ember-testing@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: |
          yarn lint:js
          yarn lint:hbs
          yarn tsc
      - name: Run Tests
        run: yarn test

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: "test"
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - uses: mydea/actions-ember-testing@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Setup dummy .env file
        run: touch .env
      - name: Run Tests
        run: yarn test:one ${{ matrix.try-scenario }}
