name: ember-cli-code-coverage

on:
  pull_request:
    branches-ignore:
      - 'dependabot/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: mydea/actions-ember-testing@v1
      - name: Install dependencies
        run: yarn install
      - uses: mydea/ember-cli-code-coverage-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
