name: Code Coverage

on: [pull_request]

jobs:
  build:

    if: github.event_name == 'pull_request' && !startsWith(github.head_ref, 'dependabot/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: rwjblue/setup-volta@v1
      - uses: mydea/actions-ember-testing@v2
      - name: Install dependencies
        run: yarn install
      - uses: mydea/ember-cli-code-coverage-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
