name: Ember CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: mydea/actions-ember-testing@v1
      with:
        node-version: ''
        yarn-version: ''
    - name: Install dependencies
      run: yarn install
    - name: Setup dummy .env file
      run: touch .env
    - name: Run tests
      run: yarn test:all
    - name: Lint
      run: |
        yarn lint:js
        yarn lint:hbs
