name: Test & Lint

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: rwjblue/setup-volta@v1
    - uses: mydea/actions-ember-testing@v2
    - name: Install dependencies
      run: yarn install
    - name: Setup dummy .env file
      run: touch .env
    - name: Run tests
      run: yarn test
    - name: Lint
      run: |
        yarn lint:js
        yarn lint:hbs
        yarn tsc

  test-matrix:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Keep this in sync with config/ember-try.js
        ember: [ember-release, ember-beta, ember-canary]

    steps:
      - uses: actions/checkout@v1
      - uses: rwjblue/setup-volta@v1
      - uses: mydea/actions-ember-testing@v2
      - name: Install dependencies
        run: yarn install
      - name: Setup dummy .env file
        run: touch .env
      - name: Run tests
        run: yarn test:one ${{ matrix.ember }}
